# Generated by Django 3.1.1 on 2020-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/Profile/images'),
        ),
    ]
